In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
t_c = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0])
t_u = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4])

In [27]:
w = torch.tensor([1.0, 0.0], requires_grad=True)
x = torch.tensor([4.0, 2.0], requires_grad=False)
b = torch.tensor([-2.0], requires_grad=True)
y = torch.tensor([5.0], requires_grad=False)

In [21]:
mul = w * x
plus = mul + b
minus = y - plus
sq = minus ** 2

In [28]:
w * x

tensor([4., 0.], grad_fn=<MulBackward0>)

In [23]:
[w, mul, b, plus, minus, sq]

[tensor([1.], requires_grad=True),
 tensor([2.], grad_fn=<MulBackward0>),
 tensor([0.], requires_grad=True),
 tensor([2.], grad_fn=<AddBackward0>),
 tensor([1.], grad_fn=<SubBackward0>),
 tensor([1.], grad_fn=<PowBackward0>)]

In [24]:
sq.backward()

In [26]:
[w.grad, mul.grad, b.grad, plus.grad, minus.grad, sq.grad]

[tensor([-4.]), None, tensor([-2.]), None, None, None]