# Deep Learning Assignment 3

    Author: Akhil Devarashetti
    Date:   01/24/2020

In [2]:
import torch
import torch.nn as nn
import pandas

In [3]:
encoder_layer = torch.nn.Linear(10, 2, bias=False)
decoder_layer = torch.nn.Linear(2, 10, bias=False)
model1 = torch.nn.Sequential(encoder_layer, decoder_layer)
optimizer = torch.optim.SGD(model1.parameters(), 1e-2)

def training_loop(n_epochs, optimizer, model, loss_fun, input_, output):
    for epoch in range(1, n_epochs+ 1):
        p = model(input_)
        loss = loss_fun(p, output)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if epoch == 1 or epoch % 1000 == 0:
            print('Epoch {}, Loss {}'.format(epoch, float(loss)))

In [4]:
data1 = pandas.read_csv("bdata1.csv")
data2 = data1.to_numpy()
data3 = torch.tensor(data2, dtype=torch.float32)

In [5]:
training_loop(
    n_epochs= 5000,
    optimizer = optimizer,
    model = model1,
    loss_fun= nn.MSELoss(),
    input_ = data3,output = data3)
print()
print(list(model1.parameters()))

Epoch 1, Loss 0.7972662448883057
Epoch 1000, Loss 0.2738717198371887
Epoch 2000, Loss 0.11064771562814713
Epoch 3000, Loss 0.09526711702346802
Epoch 4000, Loss 0.09361191838979721
Epoch 5000, Loss 0.09318778663873672

[Parameter containing:
tensor([[ 0.2744,  0.2695,  0.3444,  0.3146,  0.2980, -0.0669, -0.0376,  0.1027,
         -0.0014, -0.0547],
        [-0.0218, -0.0696, -0.3047,  0.0373,  0.0060,  0.3087,  0.1727,  0.2873,
          0.2897,  0.3150]], requires_grad=True), Parameter containing:
tensor([[ 0.6358,  0.1205],
        [ 0.5911,  0.0101],
        [ 0.6422, -0.1124],
        [ 0.6425, -0.1118],
        [ 0.7979,  0.2506],
        [ 0.2458,  0.7701],
        [ 0.0224,  0.7831],
        [ 0.2468,  0.7700],
        [ 0.2095,  0.6168],
        [ 0.0312,  0.6375]], requires_grad=True)]


In [9]:
print(data1)

   0  1  2  3  4  5  6  7  8  9
0  0  1  1  1  1  1  0  1  0  0
1  1  0  1  1  1  0  0  0  0  0
2  1  1  1  1  1  0  0  0  0  0
3  1  1  0  0  1  1  0  1  0  0
4  1  1  1  1  1  0  0  0  1  0
5  1  0  0  0  1  1  1  1  1  1
6  0  0  0  0  0  1  1  1  1  1
7  0  0  0  0  0  1  1  1  1  0
8  0  0  0  0  0  1  1  1  0  1
9  0  0  0  0  1  0  1  0  1  1


#### We can see two kinds of rows.
 - Type 1: First 5 rows mostly have 1's on the first 5 columns and 0's on the last 5 columns.
 - Type 2: Last 5 rows that mostly have 0's on the first 5 columns and 1's on the last 5 columns.

In [6]:
model2 = torch.nn.Sequential(encoder_layer)
coded_values = model2(data3)
coded_values

tensor([[ 1.2624,  0.2651],
        [ 1.2314, -0.2832],
        [ 1.5010, -0.3528],
        [ 0.8778,  0.5106],
        [ 1.4995, -0.0631],
        [ 0.5144,  1.3577],
        [-0.0580,  1.3735],
        [-0.0032,  1.0585],
        [-0.0565,  1.0838],
        [ 0.2042,  0.7835]], grad_fn=<MmBackward>)

## Both neurons in the encoder layer can distinguish the two types of rows with accuracy 90%.
 - Neuron 1: Type 1 if output > 0.5, Type 2 otherwise
 - Neuron 2: Type 1 if output <= 0.5, Type 2 otherwise

In [18]:
print("Neuron 1:")
for i in range(len(coded_values)):
    print(f"Row {i} - " + ("Type 1" if coded_values[i][0] > 0.5 else "Type 2"))
    
print("\nNeuron 2:")
for i in range(len(coded_values)):
    print(f"Row {i} - " + ("Type 2" if coded_values[i][1] > 0.5 else "Type 1"))

Neuron 1:
Row 0 - Type 1
Row 1 - Type 1
Row 2 - Type 1
Row 3 - Type 1
Row 4 - Type 1
Row 5 - Type 1
Row 6 - Type 2
Row 7 - Type 2
Row 8 - Type 2
Row 9 - Type 2

Neuron 2:
Row 0 - Type 1
Row 1 - Type 1
Row 2 - Type 1
Row 3 - Type 2
Row 4 - Type 1
Row 5 - Type 2
Row 6 - Type 2
Row 7 - Type 2
Row 8 - Type 2
Row 9 - Type 2
